---
title: "MicroMarsh"
author: "Nathan Wisnoski"
date: "8/8/2018"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(vegan)
```

# Load the data
```{r}
# read in experimental design and change classes and sample names
design <- read_csv("data/design.csv",
   col_types = cols(
     sample_ID = col_character(), 
     date = col_date(format = "%m-%Y"),
     treatment = col_factor(levels = c("C", "CS", "F", "PU", "PR"), ordered = T),
     replicate = col_integer())) %>% 
  mutate(sample_ID = paste0("s", gsub("\\_", "", sample_ID))) %>% 
  arrange(date)

# create site by species matrix
otus <- read_csv("data/cDNA iTag data.csv") %>% select(-taxonomy) %>% t()
colnames(otus) <- paste0("otu", (otus[1, ] + 1))
otus <- otus[-1,]
head(otus)[,1:10]

# make rownames of otutable match sample names
rnames <- gsub("7_1", "07_1", rownames(otus)) # make dates two digits
rnames <- gsub("3_1", "03_1", rnames)
rnames <- gsub("\\_", "", rnames) # remove underscores
rnames <- gsub("cDNA", "", rnames) # remove cDNA
rnames <- paste0("s",rnames)
rownames(otus) <- rnames

# reorder the otu table to match design
otus <- otus[match(design$sample_ID, rownames(otus)),]
all.equal.character(rownames(otus), design$sample_ID) # check that order is correct
```

# clean data
```{r}
# coverage per sample
coverage <- rowSums(otus)

# rarefy to lowest coverage
otus.rare <- rrarefy(otus, min(coverage))

# remove empty columns
otus <- otus.rare[,-which(colSums(otus.rare) == 0)]

# check number of replicates per treatment x time
design %>% group_by(date, treatment) %>% count() %>% print(n = 100)
# just subset to the two october treatments
design.sub <- design[which(months(design$date) %in% "October"),]
otus.sub <- otus[which(months(design$date) %in% "October"),]

# store full site by species matrix in otus.full and make 'otus' the subset
otus.full <- otus
otus <- otus.sub
design.full <- design
design <- design.sub
```


# Characterize alpha diversity
```{r}
otu.rich <- rowSums(decostand(otus, method = "pa"))

data.frame(otu.rich) %>% rownames_to_column("sample_ID") %>% 
  right_join(design) %>% 
  group_by(date, treatment) %>%
  ggplot(aes(x = treatment, y = otu.rich, color = treatment, fill = treatment)) +
  # geom_point(alpha = 0.5) +
  geom_boxplot(position = position_dodge(), alpha = 0.5) +
  theme_minimal() + 
  facet_grid(~ date)

rownames_to_column(data.frame(otu.rich, d1 = exp(diversity(otus, "shannon"))), "sample_ID") %>% 
  right_join(design) %>% 
  group_by(date, treatment) %>%
  ggplot(aes(x = treatment, y = otu.rich, color = treatment, fill = treatment)) +
  # geom_point(alpha = 0.5) +
  geom_boxplot(alpha = 0.5) +
  theme_minimal() + 
  facet_grid(~ date)
```


# Characterize beta diversity
```{r}
otus.hel <- decostand(otus, method = "hellinger")
otus.dist <- vegdist(otus.hel, method = "euclidean")
otus.pcoa <- cmdscale(otus.dist, eig = T)
scores(otus.pcoa)
# explained variance
explained <- round(100*eigenvals(otus.pcoa)[c(1,2)]/sum(eigenvals(otus.pcoa)),1)
as.data.frame(scores(otus.pcoa)) %>% 
  rownames_to_column("sample_ID") %>% 
  left_join(design) %>% 
  ggplot(aes(x = Dim1, y = Dim2, color = treatment, shape = factor(date))) + 
  geom_point(size = 3, alpha = 0.75) + 
  coord_fixed() + 
  theme_minimal() +
  labs(x = paste0("PCoA 1 (", explained[1],"%)"),
       y = paste0("PCoA 2 (", explained[2],"%)")) + 
  ggsave("figures/ordination.png", width = 8, height = 6, units = "in", dpi = 300)
```

